#!/bin/sh

FULLPOS=FULLPOS+2020051600

echo " start ...extract arome.... "
for RR in 00 03 06 09 12 15 18 21 24   
do
echo "extract TEMP"	
echo "extract TEMP"     
./edf namel_edf/namel_clst ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/t2m_${RR}
echo "extract TMAX"
./edf namel_edf/namel_tmax ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/tmax_${RR}
echo "extract TMIN"
./edf namel_edf/namel_tmin ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/tmin_${RR}
echo "extract HUM"
./edf namel_edf/namel_clsh ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/clsh_${RR}
echo "extract SURFACPLUIE"
./edf namel_edf/namel_acpluie ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/acpluie_${RR}
echo "extract SURFACNEIGE"
./edf namel_edf/namel_acneige ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/acneige_${RR}
echo "extract SURFEACGRAUPEL"
./edf namel_edf/namel_acgraupel ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/acgraupel_${RR}
echo "extract u-wind"
./edf namel_edf/namel_clsu ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/clsu_${RR}
echo "extract v-wind"
./edf namel_edf/namel_clsv ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/clsv_${RR}
echo "extract u-wind-raf"
./edf namel_edf/namel_uraf ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/uraf_${RR}
echo "extract v-wind-raf"
./edf namel_edf/namel_vraf ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/vraf_${RR}
echo "extract neb_bas"
./edf namel_edf/namel_nebbasse ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/neb_bas_${RR}
echo "extract neb_moy"
./edf namel_edf/namel_nebmoy ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/neb_moy_${RR}
echo "extract neb_hau"
./edf namel_edf/namel_nebhaut ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/neb_hau_${RR}
echo "extract NEB TOTAL"
./edf namel_edf/namel_nebtot ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/neb_tot_${RR}
echo "extract neb_conv"
./edf namel_edf/namel_nebconv ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/neb_conv_${RR}
echo "extract MSLP"
./edf namel_edf/namel_mslp ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/mslp_${RR}
echo "extract SURF_TOT_WAT_VAP"
./edf namel_edf/namel_wat_vap ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/wat_vap_${RR}
echo "extract SURF_CAPE"
./edf namel_edf/namel_cape ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/cape_${RR}
echo "extract ALTITUDE"
echo "extract TEMP"
./edf namel_edf/namel_temp ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/temp_${RR}
echo "extract HUM"
./edf namel_edf/namel_hum ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/hum_${RR}
echo "extract U"
./edf namel_edf/namel_U ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/u_${RR}
echo "extract V"
./edf namel_edf/namel_V ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/v_${RR}
echo "extract CLOUD WATER"
./edf namel_edf/namel_cld_wat ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/cld_wat_${RR}
echo "extract CLOUD FRAC"
./edf namel_edf/namel_cld_fra ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/cld_fra_${RR}
echo "extract ICE CRYST"
./edf namel_edf/namel_ice_cry ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/ice_cry_${RR}
echo "extract SNOW"
./edf namel_edf/namel_snow ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/snow_${RR}
echo "extract RAIN"
./edf namel_edf/namel_rain ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/rain_${RR}
echo "extract GRAUPEL"
./edf namel_edf/namel_graupel ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/graupel_${RR}
echo "extract TKE"
./edf namel_edf/namel_tke ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/tke_${RR}
echo "extract TEMP POT"
./edf namel_edf/namel_temp_pot ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/temp_pot_${RR}
echo "extract THETA PRIM"
./edf namel_edf/namel_theta_prim ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/tetha_prim_${RR}
echo "extract VERT VELOC"
./edf namel_edf/namel_vert_vel ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/vert_vel_${RR}
echo "extract POT VORT"
./edf namel_edf/namel_pot_vort ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/pot_vort_${RR}
echo "extract VITESS VE"
./edf namel_edf/namel_vvert ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/vvert_${RR}
echo "extract ABS VORT"
./edf namel_edf/namel_abs_vort ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/abs_vort_${RR}
echo "extract DIVER"
./edf namel_edf/namel_div ../data/r00/${FULLPOS}_${RR}
mv   ASCII.${FULLPOS}_${RR} ../output/r00/div_${RR}
done
rm -f INFO*
exit
